### ISSUE TITLE
a demo or gif, somewhere, anywhere would be nice :)

### ISSUE THREAD

**Issue by ilovett** [ovh-ux/ovh-angular-input-number-spinner#5]

**Comment by antleblanc** [comment]
hi @ilovett!

Here you can find a screenshot of what `<input-number-spinner/>` looks like:

![input-number-spinner](https://user-images.githubusercontent.com/428384/38234750-117bb3ac-371f-11e8-9a9a-5700150a0826.png)

I encourage you to have a look of our components library: http://master.ui-kit.ovh/#!/oui-angular/numeric
